Services:
  - type: web
    name: flask-todo-api
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn main:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todo-db
          property: connectionString